apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image
spec:
  params:
  - name: DockerLogin
    type: string
#  - name: buildcontext
#    type: string
  workspaces:
  - name: output
  - name: dockercreds
    optional: true
    mountPath: /kaniko/.docker
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      workingDir: $(workspaces.output.path)
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(workspaces.output.path)/Dockerfile
        - --destination=$(params.DockerLogin)/tekton-image
        - --context=$(workspaces.output.path)/
