apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ingress-install
spec:
  params: 
  - name: ClusteName
    type: string
  - name: StateName
    type: string
  - name: AWS-KEY
    type: string
  - name: AWS-PRIVATE-KEY
    type: string
  workspaces:
  - name: output
  steps:
  - name: ingress-install
    image: mclover45/kubernetes-kops:v2
    workingDir: $(workspaces.output.path)
    env:
    - name: AWS_ACCESS_KEY_ID
      value: $(params.AWS-KEY)
    - name: AWS_SECRET_ACCESS_KEY
      value: $(params.AWS-PRIVATE-KEY)
    - name: KOPS_STATE_STORE
      value: $(params.StateName)
    script: |
      kops export kubeconfig $(params.ClusteName) --admin 
      kops validate cluster --wait 10m
      # ingress controller install
      kubectl apply -f $(workspaces.output.path)/ingress/ic-nginx-lb.yaml
  - name: ingress-dns-check
    image: mclover45/kubernetes-kops:v2
    workingDir: $(workspaces.output.path)
    env:
    - name: AWS_ACCESS_KEY_ID
      value: $(params.AWS-KEY)
    - name: AWS_SECRET_ACCESS_KEY
      value: $(params.AWS-PRIVATE-KEY)
    - name: KOPS_STATE_STORE
      value: $(params.StateName)
    script: |
      kops export kubeconfig $(params.ClusteName) --admin
      kops validate cluster --wait 10m
      HOST_NAME_KUBE=""
      while [ -z "$HOST_NAME_KUBE"] 
      do
          HOST_NAME_KUBE=$(kubectl -n ingress-nginx get svc ingress-nginx-controller -o=jsonpath='{.status.loadBalancer.ingress[].hostname}')
          sleep 30
      done
      echo "DNS ingress in place $HOST_NAME_KUBE"
  - name: ingress-rule-creation
    image: mclover45/kubernetes-kops:v2
    workingDir: $(workspaces.output.path)
    env:
    - name: AWS_ACCESS_KEY_ID
      value: $(params.AWS-KEY)
    - name: AWS_SECRET_ACCESS_KEY
      value: $(params.AWS-PRIVATE-KEY)
    - name: KOPS_STATE_STORE
      value: $(params.StateName)
    script: |
      kops export kubeconfig $(params.ClusteName) --admin
      kubectl create namespace wordsmith
      kubectl create namespace istio-system
      kubectl apply -f ingress/app-ingress.yml