apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sops-decrypt-value
spec:
  params: 
  - name: ClusteName
    type: string
  - name: StateName
    type: string
  - name: AWS-KEY
    type: string
  - name: AWS-PRIVATE-KEY
    type: string
  - name: ARN-KEY
    type: string
  workspaces:
  - name: output
  steps:
  - name: sops-decrypt-value
    image: mclover45/kubernetes-kops:v2
    workingDir: $(workspaces.output.path)
    env:
    - name: AWS_ACCESS_KEY_ID
      value: $(params.AWS-KEY)
    - name: AWS_SECRET_ACCESS_KEY
      value: $(params.AWS-PRIVATE-KEY)
    - name: KOPS_STATE_STORE
      value: $(params.StateName)
    - name: ARN-KEY
      value: $(params.ARN-KEY)
    script: |
      sops -d -i --kms $(params.ARN-KEY) $(workspaces.output.path)/helm/wordsmith-demo/values.yaml