apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: wordsmith
  labels:
    app: {{ .Values.Database.name }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: db
  selector:
    app: {{ .Values.Database.name }}
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: words
  namespace: wordsmith
  labels:
    app: {{ .Values.API.name }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: words
  selector:
    app: {{ .Values.API.name }}
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: wordsmith
  labels:
    app: {{ .Values.WEB.name }}
spec:
  ports:  
    - port: 80
      targetPort: 80
      name: web
  selector:
    app: {{ .Values.WEB.name }}